(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/rishith/web2py/applications/IceScheduler/controllers/game.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# try something like\ndef index():\n\tgames = db(db.games.id > 0).select()\n\treturn locals()\n\ndef edit():\n\ttry:\n\t\trequest.args[0]\n\texcept IndexError:\n\t\tredirect(URL('index'))\n\tform=crud.update(db.games, request.args(0))\n\tif form.process().accepted:\n\t\tredirect(URL('index'))\n\treturn locals()\n\ndef delete():\n\ttry:\n\t\trequest.args[0]\n\texcept IndexError:\n\t\tredirect(URL('index'))\n\tdb(db.events.id == request.args(0)).delete()\n\tredirect(URL('index'))\n\treturn locals()\n\ndef add():\n\tform=crud.create(db.games)\n\tif form.process().accepted:\n\t\tredirect(URL('index'))\n\treturn locals()\n\nresponse._vars=response._caller(delete)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/rishith/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/rishith/web2py/applications/IceScheduler/controllers/game.py", line 32, in <module>\n  File "/home/rishith/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/rishith/web2py/applications/IceScheduler/controllers/game.py", line 22, in delete\n    db(db.events.id == request.args(0)).delete()\n  File "/home/rishith/web2py/gluon/packages/dal/pydal/base.py", line 906, in __getattr__\n    return super(DAL, self).__getattr__(key)\n  File "/home/rishith/web2py/gluon/packages/dal/pydal/helpers/classes.py", line 30, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.